import Head from 'next/head'

import Typography from '@material-ui/core/Typography'
import Box from '@material-ui/core/Box'

import type { InferGetServerSidePropsType } from 'next'

type TOption = {
  nextId: number
  value: number | string | boolean
  text: string
}

type TStep = {
  id: number
  name: string
  text: string
  uiType: 'button'
  valueType: 'number' | 'string' | 'boolean'
  valueOptions: TOption[]
}

export const getServerSideProps = async () => {
  const res = await fetch('https://raw.githubusercontent.com/mzronek/task/main/flow.json')
  const steps: TStep[] = await res.json()

  return {
    props: { steps },
  }
}

export default function Home({ steps }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Chat Bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box my={4}>
        <Typography variant="inherit" component="code">
          {JSON.stringify(steps, null)}
        </Typography>
      </Box>
    </>
  )
}
